##### Modfifications #####

# Dnm1 preprint
- id: doi:10.1101/2024.02.14.580336
  image: images/nucleophagy.png
  publisher: bioRxiv
  tags:
    - research article 
    - preprint

#ESCRT grommet
- id: doi:10.1038/s41556-023-01235-4
  image: https://media.springernature.com/full/springer-static/esm/art%3A10.1038%2Fs41556-023-01235-4/MediaObjects/41556_2023_1235_Fig13_ESM.jpg?as=webp
  authors:
    - Nicholas R. Ader
    - Linda Chen<sup>1</sup>
    - Ivan V. Surovtsev
    - William L. Chadwick
    - Elisa C. Rodriguez
    - Megan C. King
    - C. Patrick Lusk
  tags:
    - research article 
  description: <sup>1</sup>Undergraduate researcher

# Second Nucleophagy paper
- id: doi:10.1083/jcb.202103030
  image: images/nucleophagy0.png
  tags:
    - research article 

# First nucleophagy paper
- id: doi:10.1083/jcb.202103030
  image: images/nucleophagy0.png
  tags:
    - research article 

# PA paper
- id: doi:10.1083/jcb.202004222
  image: images/pa.png
  tags:
    - research article

#Chmpions review
- id: doi:10.1016/j.ceb.2020.01.011
  image: images/chmpions.png
  tags:
  - review

#bax
- id: doi:10.7554/elife.40712
  image: images/bax.png
  tags:
    - research article

#triclem
- id: doi:10.1016/bs.mcb.2017.03.009
  image: images/triclem.png
  title: triCLEM: Combining high-precision, room temperature CLEM with cryo-fluorescence microscopy to identify very rare events
  tags:
    - method article 

#Pink1/Parkin commentary
- id: doi:10.1523/jneurosci.2525-16.2016
  tags:
    - commentary

#Nrf2
- id: doi:10.1016/j.toxlet.2015.07.004
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/4705856/bin/nihms748068f5.jpg
  tags:
  - research article

#pivom
- id: doi:10.1002/cbic.201402382
  image: https://chemistry-europe.onlinelibrary.wiley.com/cms/asset/e22c17bf-76d2-4daf-b6f7-e41abe7a9730/mcontent.jpg
  tags:
  - research article


##### Remove old preprints #####
  
#ESCRT grommet
- id: doi:10.1101/2022.12.12.520126
  remove: true

#atg39 first paper
- id: doi:10.1101/2021.02.22.432332
  remove: true

# bax
- id: doi:10.1101/382432
  remove: true 
